//
//  Strings.h
//  SuddenRadio
//
//  Created by KIM SANG WOON on 2016. 3. 23..
//  Copyright © 2016년 KIM HYUN CHUL. All rights reserved.
//


#define errSSLCryptoString  @"Underlying cryptographic error"
#define OFFLINE_STRING  @"Offline"
#define ERROR_STRING  @"Error!"
#define LOGOUT_STRING  @"Log Out"
#define DELETE_CONVERSATIONS_ON_DISCONNECT_TITLE_STRING  @"Auto-delete"
#define DONE_STRING  @"Done"
#define noErrString  @"No Error"
#define CHATSECURE_PUSH_STRING  @"ChatSecure Push"
#define CONVERSATION_NO_LONGER_SECURE_STRING  @"The conversation with %@ is no longer secure."
#define USER_PASS_BLANK_STRING  @"You must enter a username and a password to login."
#define THEIR_FINGERPRINT_STRING  @"Purported fingerprint for"
#define errSSLPeerAuthCompletedString  @"Peer cert is valid, or was ignored if verification disabled"
#define PASSWORD_STRING  @"Password"
#define ADVANCED_STRING  @"Advanced"
#define OTRL_MSGEVENT_ENCRYPTION_REQUIRED_STRING  @"Our policy requires encryption but we are trying to send an unencrypted message out."
#define VERSION_STRING  @"Version"
#define ACCOUNT_DISCONNECTED_STRING  @"Account Disconnected"
#define INITIATE_ENCRYPTED_CHAT_STRING  @"Initiate Encrypted Chat"
#define INVALID_EMAIL_TITLE_STRING  @"Invalid Email"
#define SENDING_STRING  @"Sending"
#define OTRL_MSGEVENT_CONNECTION_ENDED_STRING  @"Message has not been sent because our buddy has ended the private conversation. We should either close the connection, or refresh it."
#define ACCOUNT_DISCONNECTED_DESCRIPTION_STRING  @"Please log into this account before managing requests."
#define ADD_STRING  @"Add"
#define OTRL_MSGEVENT_RCVDMSG_FOR_OTHER_INSTANCE_STRING  @"Received and discarded a message intended for another instance."
#define OPEN_IN_TWITTER_STRING  @"Open in Twitter"
#define TWITTER_STRING  @"Twitter"
#define CONNECTED_STRING  @"Connected"
#define TOR_WARNING_MESSAGE_STRING  @"Tor is an experimental feature, please use with caution."
#define EXTENDED_AWAY_STRING  @"Extended Away"
#define OTRL_MSGEVENT_MSG_REFLECTED_STRING  @"Received our own OTR messages."
#define errSSLClosedNoNotifyString  @"Server closed session with no notification"
#define PUBLIC_KEY_ERROR_STRING  @"Could not retrieve public key from certificate"
#define OTRL_MSGEVENT_RCVDMSG_NOT_IN_PRIVATE_STRING  @"Received an encrypted message but cannot read it because no private connection is established yet."
#define NEW_CERTIFICATE_STRING  @"New SSL Certificate"
#define LOGIN_STRING  @"Log In"
#define CANCEL_STRING  @"Cancel"
#define LOGIN_AUTOMATICALLY_STRING  @"Login Automatically"
#define errSSLPeerDecodeErrorString  @"Decoding error"
#define iOS_SSL_ERROR_PART1_STRING  @"Your current iOS system version (%@) contains a serious security vulnerability. Please update to the latest version as soon as possible."
#define errSSLRecordOverflowString  @"Record overflow"
#define errSSLDecryptionFailString  @"Decryption failure"
#define CONNECT_EXISTING_STRING  @"Connect to Existing Account"
#define GITHUB_STRING  @"GitHub"
#define OPEN_IN_FACEBOOK_STRING  @"Open in Facebook"
#define errSSLHostNameMismatchString  @"Peer host name mismatch"
#define CONVERSATION_SECURE_WARNING_STRING  @"This chat is secured"
#define PINNED_CERTIFICATES_STRING  @"Pinned Certificates"
#define DELETE_ACCOUNT_MESSAGE_STRING  @"Permanently delete"
#define OTRL_MSGEVENT_RCVDMSG_GENERAL_ERR_STRING  @"Received a general OTR error."
#define CREATED_BY_STRING  @"Created by"
#define UNLOCKED_ALERT_STRING  @"The conversation is not secure"
#define SAVE_STRING  @"Save"
#define errSSLNoRootCertString  @"Cert chain not verified by root"
#define ACCOUNTS_STRING  @"Accounts"
#define PENDING_APPROVAL_STRING  @"Pending Approval"
#define errSSLPeerDecryptionFailString  @"Decryption failed"
#define JABBER_STRING  @"Jabber (XMPP)"
#define VERIFY_STRING  @"Verify"
#define errSSLCertExpiredString  @"Chain had an expired cert"
#define errSSLBadConfigurationString  @"Configuration error"
#define ADD_BUDDY_STRING  @"Add Buddy"
#define errSSLClientCertRequestedString  @"Server has requested a client cert"
#define XMPP_TOR_STRING  @"XMPP + Tor"
#define REGISTER_ERROR_STRING  @"Error Registering Username"
#define OTRL_MSGEVENT_RCVDMSG_UNREADABLE_STRING  @"Cannot read the received message."
#define errSSLPeerProtocolVersionString  @"Bad protocol version"
#define TOR_DOMAIN_WARNING_MESSAGE_STRING  @"Only one Tor account per domain is supported at this time."
#define CHANGE_PASSPHRASE_STRING  @"Change Passphrase"
#define RECENT_STRING  @"Recent"
#define errSSLBufferOverflowString  @"Insufficient buffer provided"
#define COPY_STRING  @"Copy"
#define INCOMING_STRING  @"Incoming"
#define CONNECTING_STRING  @"Connecting"
#define LOCKED_WARN_STRING  @"The fingerprint has not been verified"
#define UNLOCK_STRING  @"Unlock"
#define DONATE_MESSAGE_STRING  @"Your donation will help fund the continued development of ChatSecure."
#define DONATE_STRING  @"Donate"
#define REJECT_STRING  @"Reject"
#define errSSLIllegalParamString  @"Illegal parameter"
#define CREATE_STRING  @"Create"
#define RESOURCE_STRING  @"Resource"
#define errSSLPeerAccessDeniedString  @"Access denied"
#define errSSLPeerInternalErrorString  @"Internal error"
#define OTRL_MSGEVENT_ENCRYPTION_ERROR_STRING  @"An error occured while encrypting a message and the message was not sent."
#define RELEASE_TO_DELETE_STRING  @"Release to delete"
#define PHOTO_LIBRARY_STRING  @"Photo Library"
#define VERIFY_FINGERPRINT_STRING  @"Verify Fingerprint"
#define SAVED_CERTIFICATES_STRING  @"Saved Certificates"
#define NEW_ACCOUNT_STRING  @"New Account"
#define DOMAIN_BLANK_ERROR_STRING  @"Domain needs to be set"
#define LOCKED_SECURE_STRING  @"The conversation is secure and the fingerprint is verfied"
#define QR_CODE_STRING  @"QR code"
#define AWAY_MESSAGE_STRING  @"is now away"
#define FACEBOOK_REMOVED_STRING  @"Facebook account removed"
#define AWAY_STRING  @"Away"
#define HOSTNAME_STRING  @"Hostname"
#define errSSLPeerInsufficientSecurityString  @"Insufficient security"
#define iOS_SSL_ERROR_TITLE_STRING  @"iOS Vulnerability"
#define HOLD_TO_TALK_STRING  @"Hold to talk"
#define SKIP_STRING  @"Skip"
#define SEARCH_STRING  @"Search"
#define AIM_STRING  @"OSCAR Instant Messenger"
#define DISCONNECTION_WARNING_DESC_STRING  @"1 Minute Alert Before Disconnection"
#define OTRL_MSGEVENT_MSG_RESENT_STRING  @"The previous message was resent."
#define CONNECT_STRING  @"Connect"
#define PAYMENTS_SETUP_ERROR_STRING  @"This device doesn't seem to be configured to make payments."
#define errSSLPeerRecordOverflowString  @"Record overflow"
#define SECURITY_STRING  @"Security"
#define errSSLPeerCertUnknownString  @"Unknown certificate"
#define ERROR_CREATING_ACCOUNT_STRING  @"Error Creating Account"
#define OTR_FINGERPRINTS_STRING  @"OTR Fingerprints"
#define errSSLPeerCertExpiredString  @"Certificate expired"
#define OTRL_MSGEVENT_SETUP_ERROR_STRING  @"A private conversation could not be set up."
#define errSSLNegotiationString  @"Cipher Suite negotiation failure"
#define errSSLPeerExportRestrictionString  @"Export restriction"
#define errSSLPeerHandshakeFailString  @"Handshake failure"
#define GOOGLE_TALK_STRING  @"Google Talk"
#define OTR_FINGERPRINTS_SUBTITLE_STRING  @"Manage OTR fingerprints"
#define errSSLFatalAlertString  @"Fatal alert"
#define iOS_SSL_ERROR_PART2_STRING  @"Settings -> General -> Software Update"
#define USERNAME_STRING  @"Username"
#define errSSLModuleAttachString  @"Module attach failure"
#define REMEMBER_PASSPHRASE_INFO_STRING  @"Your password will be stored in the iOS Keychain of this device only, and is only as safe as your device passphrase or pin. However, it will not persist during a device backup/restore via iTunes, so please don't forget it, or you may lose your conversation history."
#define WAITING_STRING  @"Waiting"
#define SHARE_STRING  @"Share"
#define OPPORTUNISTIC_OTR_SETTING_TITLE  @"Auto-start Encryption"
#define SEND_FEEDBACK_STRING  @"Send Feedback"
#define NAME_STRING  @"Name"
#define BLOCK_STRING  @"Block"
#define ACCOUNT_FINGERPRINTS_STRING  @"Account Fingerprints"
#define OK_STRING  @"OK"
#define OPPORTUNISTIC_OTR_SETTING_DESCRIPTION  @"Enables opportunistic OTR"
#define errSSLUnexpectedRecordString  @"Unexpected (skipped) record in DTLS"
#define PORT_STRING  @"Port"
#define errSSLClosedAbortString  @"Connection closed via error"
#define SUBSCRIPTION_REQUEST_TITLE  @"Subscription Requests"
#define DELETE_ACCOUNT_TITLE_STRING  @"Delete Account?"
#define errSSLPeerDecompressFailString  @"Decompression failure"
#define errSSLPeerUnsupportedCertString  @"Bad unsupported cert format"
#define OTRL_MSGEVENT_RCVDMSG_UNENCRYPTED_STRING  @"Received an unencrypted message."
#define errSSLPeerUnknownCAString  @"Unknown Cert Authority"
#define errSSLBadCipherSuiteString  @"Bad SSLCipherSuite"
#define OFFLINE_MESSAGE_STRING  @"is now offline"
#define errSSLBadRecordMacString  @"Bad MAC"
#define XMPP_FAIL_STRING  @"Failed to connect to XMPP server. Please check your login credentials and internet connection and try again."
#define errSSLPeerNoRenegotiationString  @"No renegotiation allowed"
#define EXPIRATION_STRING  @"Background session will expire in one minute."
#define errSSLInternalString  @"Internal error"
#define YOU_ARE_NOT_CONNECTED_STRING  @"You are not connected"
#define FACEBOOK_STRING  @"Facebook"
#define PUSH_TITLE_STRING  @"Push"
#define DUPLICATE_ACCOUNT_MESSAGE_STRING  @"There already exists an account with this username."
#define errSSLWouldBlockString  @"I/O would block (not fatal)"
#define CONNECTING_TO_TOR_STRING  @"Connecting to Tor"
#define CHAT_STRING  @"Chat"
#define OTRL_MSGEVENT_LOG_HEARTBEAT_RCVD_STRING  @"Received a heartbeat."
#define FACEBOOK_REMOVED_MESSAGE_STRING  @"Facebook has remmoved acces to the chat API"
#define DO_NOT_DISTURB_STRING  @"Do Not Disturb"
#define errSSLProtocolString  @"SSL protocol error"
#define SHARE_MESSAGE_STRING  @"Chat with me securely"
#define OTRL_MSGEVENT_LOG_HEARTBEAT_SENT_STRING  @"Sent a heartbeat."
#define errSSLClosedGracefulString  @"Connection closed gracefully"
#define VALID_CERTIFICATE_STRING  @"Valid certificate"
#define NEW_STRING  @"New"
#define errSSLPeerUnexpectedMsgString  @"Unexpected message received"
#define DELETE_CONVERSATIONS_ON_DISCONNECT_DESCRIPTION_STRING  @"Delete chats on disconnect"
#define CHATS_STRING  @"SA톡"
#define HELP_TRANSLATE_STRING  @"Help Translate"
#define NOT_VERIFIED_STRING  @"Not Verified"
#define errSSLPeerDecryptErrorString  @"Decryption error"
#define errSSLBadCertString  @"Bad certificate format"
#define errSSLConnectionRefusedString  @"Peer dropped connection before responding"
#define SECURITY_WARNING_STRING  @"Security Warning"
#define VERIFIED_STRING  @"Verified"
#define BUDDY_INFO_STRING  @"Buddy Info"
#define NEW_PASSPHRASE_STRING  @"New Passphrase"
#define ACCOUNT_STRING  @"Account"
#define QR_CODE_INSTRUCTIONS_STRING  @"This QR Code contains a link to http://omniqrcode.com/q/chatsecure and will redirect to the App Store."
#define REMEMBER_PASSWORD_STRING  @"Remember password"
#define CONVERSATION_NOT_SECURE_WARNING_STRING  @"Warning: This chat is not encrypted"
#define CANCEL_ENCRYPTED_CHAT_STRING  @"Cancel Encrypted Chat"
#define SETTINGS_STRING  @"Settings"
#define ENCRYPTION_ERROR_STRING  @"Encryption Error"
#define LOCKED_ERROR_STRING  @"The fingerprint has changed and needs to be verified"
#define SIGN_UP_STRING  @"Sign Up"
#define REMEMBER_PASSPHRASE_STRING  @"Remember Passphrase"
#define MANAGE_CHATSECURE_PUSH_ACCOUNT_STRING  @"Manage ChatSecure Push account"
#define errSSLPeerBadCertString  @"Miscellaneous bad certificate"
#define OLD_STRING  @"Old"
#define FORGOT_PASSPHRASE_INFO_STRING  @"Because the database contents is encrypted with your passphrase, you've lost access to your data and will need to delete and reinstall ChatSecure to continue. Password managers like 1Password or MiniKeePass can be helpful for generating and storing strong passwords."
#define SOURCE_STRING  @"Check out the source here on Github"
#define DATABASE_PASSPHRASE_CHANGE_SUCCESS_STRING  @"The database passphrase change was successful."
#define errSSLSessionNotFoundString  @"Attempt to restore an unknown session"
#define INFO_STRING  @"Info"
#define OTHER_STRING  @"Other"
#define REPLY_STRING  @"Reply"
#define IN_BAND_ERROR_STRING  @"The XMPP server does not support in-band registration"
#define AVAILABLE_STRING  @"Available"
#define CREATE_NEW_ACCOUNT_STRING  @"Create New Account"
#define errSSLPeerBadRecordMacString  @"Bad MAC"
#define OPTIONAL_STRING  @"Optional"
#define errSSLCertNotYetValidString  @"Chain had a cert not yet valid"
#define errSSLPeerUserCancelledString  @"User canceled"
#define DELIVERED_STRING  @"Delivered"
#define ABOUT_STRING  @"About"
#define REQUIRED_STRING  @"Required"
#define INVALID_EMAIL_DETAIL_STRING  @"Please choose a valid email address"
#define YOUR_FINGERPRINT_STRING  @"Fingerprint for you"
#define COMPOSE_STRING  @"Compose"
#define FORGOT_PASSPHRASE_STRING  @"Forgot Passphrase?"
#define NEXT_STRING  @"Next"
#define DUPLICATE_ACCOUNT_STRING  @"Duplicate account"
#define BASIC_STRING  @"Basic"
#define LANGUAGE_STRING  @"Language"
#define errSSLUnknownRootCertString  @"Valid cert chain, untrusted root"
#define SET_NEW_DATABASE_PASSPHRASE_STRING  @"Set new database passphrase"
#define AVAILABLE_MESSAGE_STRING  @"is now available"
#define OTRL_MSGEVENT_RCVDMSG_MALFORMED_STRING  @"The message received contains malformed data."
#define DATABASE_PASSPHRASE_CHANGE_ERROR_STRING  @"An error occurred while changing the database passphrase."
#define BLOCK_AND_REMOVE_STRING  @"Block & Remove"
#define CREATING_ACCOUNT_STRING  @"Creating Account"
#define DATABASE_SETUP_ERROR_STRING  @"An error occurred while setting up the database."
#define XMPP_PORT_FAIL_STRING  @"Domain needs to be set manually when specifying a custom port"
#define DISCONNECTION_WARNING_TITLE_STRING  @"Sign out Warning"
#define BUDDY_LIST_STRING  @"Buddy List"
#define errSSLPeerCertRevokedString  @"Certificate revoked"
#define VERIFY_LATER_STRING  @"Verify Later"
#define LOGGING_IN_STRING  @"Logging in..."
#define OTRL_MSGEVENT_RCVDMSG_UNRECOGNIZED_STRING  @"Cannot recognize the type of OTR message received."
#define SSL_MISMATCH_STRING  @"SSL Hostname Mismatch"
#define RELEASE_TO_SEND_STRING  @"Release to send"
#define errSSLXCertChainInvalidString  @"Invalid certificate chain"
#define EMAIL_STRING  @"Email"
#define XMPP_USERNAME_EXAMPLE_STRING  @"user@example.com"
#define OPEN_IN_CHROME  @"Open in Chrome"
#define SECURE_CONVERSATION_STRING  @"You must be in a secure conversation first."
#define SHOW_USERVOICE_STRING  @"Would you like to connect to UserVoice to send feedback?"
#define CURRENT_PASSPHRASE_STRING  @"Current Passphrase"
#define SELF_SIGNED_SSL_STRING  @"Self Signed SSL"
#define ABOUT_VERSION_STRING  @"About This Version"
#define USE_CAMERA_STRING  @"Take Photo or Video"
#define BUDDY_FINGERPRINTS_STRING  @"Buddy Fingerprints"
#define PINNED_CERTIFICATES_DESCRIPTION_STRING  @"Manage saved SSL certificates"
#define REMOVE_STRING  @"Remove"
#define DEFAULT_LANGUAGE_STRING NSLocalizedString(@"Default", @"default string to revert to normal language behaviour")
